### ISSUE TITLE
How can the API mock be used on a build server?

### ISSUE THREAD

**Issue by awarberg** [SalesforceCommerceCloud/dw-api-mock#18]
We would like to run the tests on the build server as part of the pull request validation, but it seems like it is not possible when following the sample package.json due to an access rights issue:

```
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@bitbucket.org/demandware/dw-api-mock.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```

Is there anywhere else I can get the module from that is not password protected (I looked at npmjs and it doesn't have it)? Or do I need to copy the dw-api-mock repository into my own repository?

**Comment by dmersiowsky** [comment]
Hi, this repository is protected (and will probably be), so the only way of solving this is to copy the mocks into your project repository.
