### ISSUE TITLE
Unable to mock a HTTPForm service

### ISSUE THREAD

**Issue by aduponchel** [SalesforceCommerceCloud/dw-api-mock#24]
https://github.com/SalesforceCommerceCloud/dw-api-mock/blob/cfc46f8fbd644772e7491e462e47d528cb20a1d9/dw/svc/LocalServiceRegistry.js#L17

as service id is lowercased, 'httpForm' will never match

**Comment by dmersiowsky** [comment]
It's literally a single character change, appreciate if you could create a PR real quick next time. Thanks!

**Comment by aduponchel** [comment]
I thought the repository was dead, since no pull request were handled from 2022.
I probably wrote this issue anyway to prevent others and avoid them to loose time debugging.
However I am happy to see this repository alive. Thank you for maintaining it !
